### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by kellyselden** [tomdale/ember-cli-addon-tests#156]
https://github.com/emberjs/data/issues/5177

**Comment by simonihmig** [comment]
Good catch! Have seen this strict mode error as well (https://github.com/DockYard/ember-service-worker/pull/87), glad I don't have to dig into this...

Not sure why we include ember-data by default, and why this has to be master (which is probably more error prone than a stable release). Should we rethink that?

**Comment by kellyselden** [comment]
It's there for legacy reasons, when ember-data was getting working towards fastboot compatibility on master, and when ember-data was included in addons by default (not anymore). Maybe @tomdale has an opinion on whether it should be opt-in now or non-master. Line for reference https://github.com/tomdale/ember-cli-addon-tests/blob/2802a08cd27d91ee44aa835d0cc0d21e7228b42d/lib/utilities/pristine.js#L98.

**Comment by kellyselden** [comment]
Working now.
