### ISSUE TITLE
Throws with portfinder@1.0.22

### ISSUE THREAD

**Issue by jelhan** [tomdale/ember-cli-addon-tests#212]
Portfinder 1.0.22 released a few hours ago [reduced the default `highestPort` from `65535` to `40000`](https://github.com/http-party/node-portfinder/compare/v1.0.21...v1.0.22). This addon uses port `49741` by default: https://github.com/tomdale/ember-cli-addon-tests/blob/6e4d2bd20efce50b3236980e4ac211c98962d9d4/lib/commands/start-server.js#L13

Since `49741 > 40000` and it doesn't pass a custom`highestPort` option, portfinder throws:

> Provided options.stopPort(40000is less than options.startPort (49741)

**Comment by jelhan** [comment]
It's the same error as if running `ember serve --port 49741` with `portfinder@1.0.22`.

**Comment by rwjblue** [comment]
FYI - portfinder@1.0.23 was released with the same code as 1.0.21 to mitigate issues while they figure out the fix forward.
