### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by kellyselden** [tomdale/ember-cli-addon-tests#39]
It has a fix for Windows. Should probably be minor up to v0.5.0 because of the heavy refactoring.

**Comment by simonihmig** [comment]
Also thought about this after your PRs landed, but back then I thought there were just internal changes (added tests, refactorings), nothing relevant to the consumer of the package. However probably overlooked the Windows support that was added in #24, right? (PR's title did not mention this)

So this would justify a release very much then! 👍 
You can do that by yourself, right?

**Comment by kellyselden** [comment]
> You can do that by yourself, right?

I don't have npm access.

**Comment by simonihmig** [comment]
Published as 0.5.0
