### ISSUE TITLE
Possible regression after 0.4.2

### ISSUE THREAD

**Issue by simonihmig** [tomdale/ember-cli-addon-tests#49]
See https://github.com/simplabs/ember-simple-auth/pull/1198

**Comment by kellyselden** [comment]
I have a suspicion that https://github.com/tomdale/ember-cli-addon-tests/pull/24 is the cause. I won't have time to dig until after Wednesday, but I would not be upset if someone reverted it in the meantime.

**Comment by simonihmig** [comment]
Unfortunately I don't have much time right now for this neither. @Turbo87 spent quite some time on this today, see the linked issue. Workaround was to run `ember build` before starting FastBoot. 

It seems this was hard-coded in this addon before merging #24: 
https://github.com/tomdale/ember-cli-addon-tests/pull/24/files#diff-472a0e82d7dd0a4e6a858bd4a14f9270L42

While reverting that PR might "fix" that issue, it probably is just hiding the real issue. Have no proof thereof, but might be related to https://github.com/ember-fastboot/ember-cli-fastboot/issues/246. Needs some investigation...

**Comment by kellyselden** [comment]
Cool nice find on the build missing. I probably thought I was optimizing it out successfully. Maybe putting it back in would be the bandaid required.

It sucks though that this issue won't show up in our own tests.

**Comment by simonihmig** [comment]
@kellyselden maybe it does not show up in tests because it is FastBoot-related, as my suspicion was. We are testing `ember serve` in our acceptance test. 

Not sure why there was an explicit `ember build` before running the server, as this seems wasteful at first look. @tomdale can you recall that? -> https://github.com/tomdale/ember-cli-addon-tests/blob/6266f54cb5f99103a9e4c936bfb59288883fbdaa/lib/commands/start-server.js#L42-L45

**Comment by kellyselden** [comment]
I'd be cool with putting it back with a comment like `// fastboot needs this, but why?`

**Comment by Turbo87** [comment]
the issue seems to be that fastboot expects the build output in `dist`, but `ember serve` builds into `tmp` and I guess `ember fastboot` is now building into `tmp` too but still serving from `dist` maybe?

**Comment by simonihmig** [comment]
But running `ember fastboot` locally is working perfectly without running `ember build` before, even with an empty `dist` folder. Builds (which is populating `dist`) and then serves it.

**Comment by Turbo87** [comment]
yeah, that's the weird part that I haven't been able to figure out. it also seems to work fine when we used it like this in `ember-cookies`, but for `ember-simple-auth` it kept failing whatever I was doing.

**Comment by kellyselden** [comment]
@simonihmig @Turbo87 I've added a fastboot acceptance test here. I thought it would have triggered this bug, but it passes. Can you think of anything else that the test is missing to trigger the bug?

**Comment by simonihmig** [comment]
Again, this is more speculation than the result of clear evidence, but I think the root cause might be something different, which just has been uncovered by removing the (redundant) separate build step, possibly this https://github.com/ember-fastboot/ember-cli-fastboot/issues/246?

When writing tests for an app (using https://github.com/kaliber5/ember-fastboot-app-tests which uses the latest release of this package), I could not reproduce the issues @Turbo87 had. And as he said, tests were working fine for `ember-cookie` but failing for `ember-simple-auth` (the latter being "fixed" by an additional build step).

I have the suspicion that it might be related to `e-s-a` creating two "under-test" apps, while all the other examples that are working fine create just one app. Still pure speculation though...

**Comment by Turbo87** [comment]
> I have the suspicion that it might be related to e-s-a creating two "under-test" apps, while all the other examples that are working fine create just one app. Still pure speculation though...

e-s-a is indeed creating two apps, but the first one already failed so I'm not sure if that is really related 🤷‍♂️

**Comment by kellyselden** [comment]
I'm using it in 3 projects. it fails in 2 and still passes in one after 0.4.2:
https://github.com/kellyselden/ember-macro-test-helpers/pull/9
https://github.com/kellyselden/ember-data-fetch-support/pull/43
https://github.com/kellyselden/ember-cli-node-modules-to-vendor/pull/18

Maybe this can help narrow it down?

**Comment by simonihmig** [comment]
Ok guys, I investigated this a bit more deeply today, and I think it is clear now.

The root issue is indeed https://github.com/ember-fastboot/ember-cli-fastboot/issues/246. When I cd into the under-test app folder and run `ember fastboot` (regardless of which `ember` executable is used), it fails with the same error for the first time, while it succeeds when runnning that the second time (when there is already a build in `dist`). When I clear `dist` again, it fails again for the first time.

Not sure what the conditions are for this to fail (as it is working for some addons), but as the issue mentioned above is mentioning race conditions, this would probably explain the not always reproducable nature of this error...

https://github.com/ember-fastboot/ember-cli-fastboot/pull/269 seems to have fixed it, because when I replace https://github.com/simplabs/ember-simple-auth/blob/master/fastboot-tests/integration-test.js#L72 with...

```js
pkg['devDependencies']['ember-cli-fastboot'] = "ember-fastboot/ember-cli-fastboot#master";
```

... then it works again, even without the additional build step added here: https://github.com/simplabs/ember-simple-auth/pull/1198/commits/ee7cdf4688c676deb50098fa0fef1fc5a6c039c8

Have not tested that with the other addons of @kellyselden, but I am pretty sure one of these workarounds (additional build command, or latest `ember-cli-fastboot`) should fix this.

I would not really like to add the build step workaround to this addon as was suggested, as the issue is somewhere else, and is also affecting running FastBoot only, while there are good use cases for this addon besides FastBoot testing (like just testing `ember serve` for some addon-generated build artefacts), and this additional build step would be useless there. I suspect the error to be gone anyways with the next release of `ember-cli-fastboot`.

So closing this for now.
