### ISSUE TITLE
Does not work without Bower

### ISSUE THREAD

**Issue by trentmwillis** [tomdale/ember-cli-addon-tests#75]
In newer versions of Ember-CLI, Bower is optional. In those cases, this can blow up since the `bower` global may not be available in the CI environment.

Ref: https://github.com/ember-engines/ember-engines/pull/374

**Comment by trentmwillis** [comment]
Seems like this is also related to not supporting `ember-source` right now. I'm going to work on back-filling tests and then trying to add more features.

**Comment by simonihmig** [comment]
@trentmwillis are you going to work on this in the near future? I also have a need to get this fixed. I hope to find the time over the weekend, but don't want to duplicate efforts...

**Comment by trentmwillis** [comment]
@simonihmig I'm planning on working on it today as it is now blocking upgrades for ember-engines.

**Comment by trentmwillis** [comment]
This should be fixed for `ember-cli@>2.13.0` by #91 but you'll still need Bower for older versions of Ember-CLI. I'm going to close this as the recommended path forward for not using Bower should just be to upgrade IMO.
