### ISSUE TITLE
Second test app fails because of missing .eslintrc.js

### ISSUE THREAD

**Issue by simonihmig** [tomdale/ember-cli-addon-tests#81]
When using this with new ember-cli versions (tested 2.12.0), the first test app runs fine, but starting the server on a second test app fails with `Error: No ESLint configuration found.`.

This is because here (https://github.com/tomdale/ember-cli-addon-tests/blob/master/lib/utilities/pristine.js#L81) we create the second app (when `node_modules` exists) with the `--skip-npm` flag, but this flag causes ember-cli to skip running the `ember-cli-eslint` blueprint, see https://github.com/ember-cli/ember-cli/blob/bd2822868e3b9bf11cfa9f28b91cb4d021c6680b/lib/commands/init.js#L100.

Not sure how to best fix this...
* in ember-cli (by not looking at the skip flag, but by checking if we can `require` ember-cli-eslint)
* in ember-cli-eslint (by not failing because of a missing `.eslintrc.js`)
* here as a workaround (by running the blueprint if the addon is a dependency but not initialized correctly)

cc @Turbo87 @rwjblue

**Comment by kellyselden** [comment]
I think this is fixed on ember-cli 2.12.1

**Comment by simonihmig** [comment]
@kellyselden You are right, thanks!
